#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$PG_USER" --dbname "test_2018" <<-EOSQL

REVOKE ALL PRIVILEGES ON DATABASE test_2018 FROM replikant2;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM replikant2;
DROP ROLE IF EXISTS replikant2;
CREATE ROLE replikant2 WITH REPLICATION LOGIN PASSWORD 'repliciram2';
GRANT ALL PRIVILEGES ON DATABASE test_2018 TO replikant2;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO replikant2;


DROP SUBSCRIPTION IF EXISTS subscription_1;
-- centos1 = 192.168.124.245
CREATE SUBSCRIPTION subscription_1 CONNECTION 'host=192.168.124.245 port=5432 password=repliciram user=replikant dbname=test_2018' PUBLICATION publication_1;


DROP PUBLICATION IF EXISTS publication_2;
REVOKE ALL PRIVILEGES ON DATABASE test_2018 FROM replikant2;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM replikant2;

CREATE PUBLICATION publication_2;
ALTER PUBLICATION publication_2 ADD TABLE roba;

EOSQL