
function KALK_IMP_BRISI_TXT()



function CRE_KALK_PRIPRT()


function GET_KALK_14_DATVAL()

function UPDATE_KALK_14_DATVAL()

function KALK_IMP_OBRADI_SVE_DOKUMENTE_IZ_PRIPT()

function KALK_IMP_PARTN_EXIST()

function  KALK_IMP_TXT_PARAM_AUTO_IMPORT_PODATAKA_KONTO()


function KALK_PRIPR_AUTO_OBRADA_I_AZURIRANJE()
