#!/bin/bash

echo "dump f18 test"

HOST=localhost
USER=postgres
PGPASSWORD=admin
SQL=test/data/f18_test.sql
DATABASE=f18_test
echo "DROP DATABASE f18_test; CREATE database f18_test" | psql -h $HOST -U $USER

echo "restore from $SQL"
psql -h $HOST -U $USER $DATABASE < $SQL 

echo "select count(*) from fmk.konto" | psql -h $HOST -U $USER $DATABASE
