#!/bin/bash


HOST=localhost
USER=postgres
PGPASSWORD=admin
DATABASE=f18_test

export PGPASSWORD="admin"

echo "brisem fmk.log tabelu"
#echo "delete from fmk.log" | psql -h $HOST -U $USER $DATABASE
echo "dump f18_test"
pg_dump -h $HOST -U $USER  f18_test > test/data/f18_test.sql
